baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Material design 3 Hugo theme'
sectionPagesMenu = 'main'

[module]
[module.hugoVersion]
extended = false
min = "0.116.0"

[params]
name = "Raphaël Weis"
tagline = "French software engineering student."
