name = 'Md3'
license = 'MIT'
licenselink = 'https://github.com/owner/repo/LICENSE'
description = 'Material design 3 inspired theme for Hugo.'
# Not created yet
# homepage = 'https://github.com/raphaelweis/hugo-md3-theme'

[author]
  name = 'Raphaël Weis'
  homepage = 'raphaelweis.com'
