name = 'hugo-md3-theme'
license = 'MIT'
licenselink = 'https://github.com/raphaelweis/hugo-md3-theme/LICENSE'
description = 'Material design 3 inspired theme for Hugo.'
homepage = 'https://github.com/raphaelweis/hugo-md3-theme'

[author]
  name = 'Raphaël Weis'
  homepage = 'https://raphaelweis.com'
